config/routes.rb
Rails.application.routes.draw do
  resources :hungry_people
  resources :dishes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :orders
  has_many :hungry_people, through: :orders
end

app/models/hungry_person.rb
class HungryPerson < ApplicationRecord
  has_many :orders
  has_many :dishes, through: :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :hungry_person
  belongs_to :dish
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_hungry_person
  before_filter :require_hungry_person

private

  def current_hungry_person
    @current_hungry_person ||= HungryPerson.where(:id => session[:hungry_person_id])
  end

  def require_hungry_person
    unless current_hungry_person
      flash[:notice] = "Πρέπει να επιλέξετε πειναλέο παρακαλώ"
      redirect_to hungry_people_url
      return false
    end
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_filter :require_hungry_person, :except => [:new, :create, :index]
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
    @orders = Order.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :image_url, :price)
    end
end

app/controllers/hungry_people_controller.rb
class HungryPeopleController < ApplicationController
  before_action :set_hungry_person, only: [:show, :edit, :update, :destroy]

  # GET /hungry_people
  # GET /hungry_people.json
  def index
    @hungry_people = HungryPerson.all
  end

  # GET /hungry_people/1
  # GET /hungry_people/1.json
  def show
    session[:hungry_person_id] = params[:id]
  end

  # GET /hungry_people/new
  def new
    @hungry_person = HungryPerson.new
  end

  # GET /hungry_people/1/edit
  def edit
  end

  # POST /hungry_people
  # POST /hungry_people.json
  def create
    @hungry_person = HungryPerson.new(hungry_person_params)

    respond_to do |format|
      if @hungry_person.save
        format.html { redirect_to @hungry_person, notice: 'Hungry person was successfully created.' }
        format.json { render :show, status: :created, location: @hungry_person }
      else
        format.html { render :new }
        format.json { render json: @hungry_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hungry_people/1
  # PATCH/PUT /hungry_people/1.json
  def update
    respond_to do |format|
      if @hungry_person.update(hungry_person_params)
        format.html { redirect_to @hungry_person, notice: 'Hungry person was successfully updated.' }
        format.json { render :show, status: :ok, location: @hungry_person }
      else
        format.html { render :edit }
        format.json { render json: @hungry_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hungry_people/1
  # DELETE /hungry_people/1.json
  def destroy
    @hungry_person.destroy
    respond_to do |format|
      format.html { redirect_to hungry_people_url, notice: 'Hungry person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hungry_person
      @hungry_person = HungryPerson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hungry_person_params
      params.require(:hungry_person).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/hungry_people_helper.rb
module HungryPeopleHelper
end

app/views/dishes/_form.html.erb
<%= form_for(dish) do |f| %>
  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Πιάτα ημέρας</h1>

<div class="row">
  <% @dishes.each do |dish| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag dish.image_url %>
        <div class="caption">
          <h3><%= dish.name %></h3>
          <h2><%= dish.price %>€</h2>
          <p><%= link_to 'Επεξεργασία', edit_dish_path(dish), {:class=>"btn btn-primary"} %>
            <%= link_to 'Διαγραφή', dish, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></p>
        </div>
      </div>
    </div>
  <% end %>

  <%= link_to 'Νέο πιάτο', new_dish_path, class: "btn btn-default"  %>

</div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Ποιοι πεινάνε στο coho αυτή τη στιγμή</div>
  <div class="panel-body">
    <p>Παρακάτω είναι όλοι όσοι πεινάνε στο coho και τι θέλουν να φάνε.</p>
  </div>

  <!-- Table -->
  <table class="table">
    <% @orders.each do |order| %>
      <tr>
        <td>
          <%= order.hungry_person.name %>
        </td>
        <td>
          <%= order.dish.name %>
        </td>
        <td>
          <%= order.quantity %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @dish.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/hungry_people/_form.html.erb
<%= form_for(hungry_person) do |f| %>
  <% if hungry_person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hungry_person.errors.count, "error") %> prohibited this hungry_person from being saved:</h2>

      <ul>
      <% hungry_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hungry_people/edit.html.erb
<h1>Editing Hungry Person</h1>

<%= render 'form', hungry_person: @hungry_person %>

<%= link_to 'Show', @hungry_person %> |
<%= link_to 'Back', hungry_people_path %>

app/views/hungry_people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hungry People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hungry_people.each do |hungry_person| %>
      <tr>
        <td><%= hungry_person.name %></td>
        <td><%= link_to 'Επιλογή', hungry_person %></td>
        <td><%= link_to 'Edit', edit_hungry_person_path(hungry_person) %></td>
        <td><%= link_to 'Destroy', hungry_person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hungry Person', new_hungry_person_path %>

app/views/hungry_people/new.html.erb
<h1>New Hungry Person</h1>

<%= render 'form', hungry_person: @hungry_person %>

<%= link_to 'Back', hungry_people_path %>

app/views/hungry_people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hungry_person.name %>
</p>

<%= link_to 'Edit', edit_hungry_person_path(@hungry_person) %> |
<%= link_to 'Back', hungry_people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mageriko</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Mageriko</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if session[:hungry_person_id] %>
          <p class="navbar-text">Signed in as <%= HungryPerson.find_by_id(session[:hungry_person_id]).name %></p>
        <% else %>
          <p class="navbar-text"><%= link_to 'Παρακαλώ επιλέξτε ποια/ποιος πειναλέος είστε', hungry_people_path %></p>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <%= yield %>
  </body>
</html>